using System;
using System.Collections.Generic;
using System.Linq;
using Wish;

namespace CreativeMode;

public static class DecorationCategorization
{
    private static List<int> _allItems;

    private static Dictionary<int, string> _dlcAssociation = new()
    {
        { ItemID.PirateAnchor, "SeasideDLC" },
        { ItemID.PirateBed, "SeasideDLC" },
        { ItemID.PirateCannon, "SeasideDLC" },
        { ItemID.PirateChair, "SeasideDLC" },
        { ItemID.PirateChest, "SeasideDLC" },
        { ItemID.PirateHammock, "SeasideDLC" },
        { ItemID.PirateTable, "SeasideDLC" },
        { ItemID.PirateTreasureMap, "SeasideDLC" },
        { ItemID.PirateWardrobe, "SeasideDLC" },
        { ItemID.PirateWoodPost, "SeasideDLC" },
        { ItemID.SeasideBed, "OceanShoreDLC" },
        { ItemID.SeasideChair, "OceanShoreDLC" },
        { ItemID.SeasideChest, "OceanShoreDLC" },
        { ItemID.SeasideEndTable, "OceanShoreDLC" },
        { ItemID.SeasideLamp, "OceanShoreDLC" },
        { ItemID.SeasideTable, "OceanShoreDLC" },
        { ItemID.SeasideWardrobe, "OceanShoreDLC" },
        { ItemID.BlueSeasideShellRug, "OceanShoreDLC" },
        { ItemID.BlueSeasideStarfishRug, "OceanShoreDLC" },
        { ItemID.PinkSeasideShellRug, "OceanShoreDLC" },
        { ItemID.PinkSeasideStarfishRug, "OceanShoreDLC" },
        { ItemID.MushroomBed, "MushyDLC" },
        { ItemID.MushroomBookshelf, "MushyDLC" },
        { ItemID.MushroomCarpet, "MushyDLC" },
        { ItemID.MushroomCoatRack, "MushyDLC" },
        { ItemID.MushroomTable, "MushyDLC" },
        { ItemID.MushroomEndTable, "MushyDLC" },
        { ItemID.RedMushroomDecoration, "MushyDLC" },
        { ItemID.LightBrownMushroomDecoration, "MushyDLC" },
        { ItemID.Brimmy, "SpookyPetDLC" },
        { ItemID.Webster, "SpookyPetDLC" },
        { ItemID.Nevermore, "SpookyPetDLC" },
        { ItemID.Noire, "SpookyPetDLC" },
        { ItemID.Fangy, "SpookyPetDLC" },
        { ItemID.Pips, "CutePetDLC" },
        { ItemID.Chipper, "CutePetDLC" },
        { ItemID.Pinkadee, "CutePetDLC" },
        { ItemID.Ursil, "CutePetDLC" },
        { ItemID.Sweetie, "CutePetDLC" },
        { ItemID.Scuttles, "SeasideDLC" },
        { ItemID.Sam, "SeasideDLC" },
        { ItemID.Mips, "SeasideDLC" },
        { ItemID.Booshroom, "MushyDLC" },        
        // TrickOrTreatDLC
        { ItemID.Willo, "TrickOrTreatDLC"},
        { ItemID.SpookyRug, "TrickOrTreatDLC"},
        { ItemID.SpookyBed, "TrickOrTreatDLC"},
        { ItemID.SpookyWardrobe, "TrickOrTreatDLC"},
        { ItemID.SpookyCouch, "TrickOrTreatDLC"},
        { ItemID.SpookyChair, "TrickOrTreatDLC"},
        { ItemID.SpookyEndTable, "TrickOrTreatDLC"},
        { ItemID.SpookyTable, "TrickOrTreatDLC"},
        { ItemID.SpookyPumpkinCauldron, "TrickOrTreatDLC"},
        { ItemID.SpookyStackofPumpkins, "TrickOrTreatDLC"},
        // RockNRollDLC
        { ItemID.Slash, "RockNRollDLC"},
        { ItemID.RocknRollCouch, "RockNRollDLC"},
        { ItemID.RocknRollAmp, "RockNRollDLC"},
        { ItemID.RocknRollBlackGuitar, "RockNRollDLC"},
        { ItemID.RocknRollRedGuitar, "RockNRollDLC"},
        { ItemID.RocknRollWardrobe, "RockNRollDLC"},
        { ItemID.RocknRollLamp, "RockNRollDLC"},
        { ItemID.RocknRollGoldRecordAward, "RockNRollDLC"},
        { ItemID.RocknRollBed, "RockNRollDLC"},
        { ItemID.RocknRollTable, "RockNRollDLC"},
        { ItemID.RocknRollEndTable, "RockNRollDLC"},
        { ItemID.RocknRollBlackRug, "RockNRollDLC"},
        { ItemID.RocknRollRedRug, "RockNRollDLC"},
        // FunkyMonkeyDLC
        { ItemID.Funky, "FunkyMonkeyDLC"},
        // DreamyRamDLC
        { ItemID.Daydream, "DreamyRamDLC"},
        // CyberPopDLC
        { ItemID.S1FER, "CyberPopDLC"},
        { ItemID.QU4CK, "CyberPopDLC"},
        { ItemID.MOUS3, "CyberPopDLC"},
        { ItemID.Ellis, "CyberPopDLC"},
        { ItemID.Lewey, "CyberPopDLC"},
        { ItemID.CyberpopThrone, "CyberPopDLC"},
        { ItemID.CyberpopBicycle, "CyberPopDLC"},
        { ItemID.CyberpopHoverBike, "CyberPopDLC"},
        { ItemID.CyberpopMotorcycle, "CyberPopDLC"},
        { ItemID.CyberpopBed, "CyberPopDLC"},
        { ItemID.CyberpopCouch, "CyberPopDLC"},
        { ItemID.CyberpopStudentChest, "CyberPopDLC"},
        { ItemID.CyberpopWardrobe, "CyberPopDLC"},
        { ItemID.CyberpopArcCapacitor, "CyberPopDLC"},
        { ItemID.CyberpopRecordPlayer, "CyberPopDLC"},
        { ItemID.CyberpopStudentChair, "CyberPopDLC"},
        { ItemID.CyberpopGlobe, "CyberPopDLC"},
        { ItemID.CyberpopDesk, "CyberPopDLC"},
        { ItemID.CyberpopTable, "CyberPopDLC"},
        { ItemID.CyberpopRug, "CyberPopDLC"},
        // SpiritPetalDLC
        { ItemID.Ixi, "SpiritPetalDLC" },
        { ItemID.SpiritOrb, "SpiritPetalDLC" },
        { ItemID.SpiritPetalLamp, "SpiritPetalDLC" },
        { ItemID.SpiritPetalWardrobe, "SpiritPetalDLC" },
        { ItemID.SpiritPetalCouch, "SpiritPetalDLC" },
        { ItemID.SpiritPetalChair, "SpiritPetalDLC" },
        { ItemID.SpiritPetalEndTable, "SpiritPetalDLC" },
        { ItemID.SpiritPetalTable, "SpiritPetalDLC" },
        { ItemID.SpiritPetalRug, "SpiritPetalDLC" },
        { ItemID.SpiritPetalBed, "SpiritPetalDLC" },
    };

    public static DecorationCategory GetCategoryId(string name)
    {
        return CategoryNames.FirstOrDefault(c => c.Value.Equals(name)).Key;
    }

    public static List<int> GetMatchingItemIds(DecorationCategory category, string search, int offset, int limit)
    {
        if (category == DecorationCategory.None || !Categories.TryGetValue(category, out var baseItems))
        {
            baseItems = GetAllItems();
        }

        var s = baseItems.Select(s => s);

        if (!Plugin.ShowUnownedDLCItems.Value)
        {
            s = s.Select(i => new { id = i, ItemDatabase.GetItemData(i).isDLCItem })
                .Where(arg => !arg.isDLCItem || DecorationCategorization.canUseDlcItem(arg.id))
                .Select(arg => arg.id);
        }

        if (!search.Equals(""))
        {
            var splitSearch = search.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            s = s.Select(i => new { id = i, ItemDatabase.GetItemData(i).name })
                .Where(arg => splitSearch.Count(searchWord => arg.name.IndexOf(searchWord, StringComparison.OrdinalIgnoreCase) >= 0) == splitSearch.Length)
                .OrderBy(arg => LevenshteinDistance(search, arg.name))
                .ThenBy(arg => arg.name)
                .Select(arg => arg.id);
        }
        else
        {
            s = s.OrderBy(x => ItemDatabase.GetItemData(x).name);
        }

        return s.Skip(offset).Take(limit + 1).ToList();
    }

    public static bool canUseDlcItem(int itemId)
    {
        return _dlcAssociation.ContainsKey(itemId) && GameSave.Instance.GetProgressBoolCharacter(_dlcAssociation[itemId]);
    }

    private static List<int> GetAllItems()
    {
        if (_allItems == null)
        {
            var all = new List<int>();

            foreach (var x in Categories.Values)
            {
                all.AddRange(x);
            }

            _allItems = all.Distinct().ToList();
        }

        return _allItems;
    }
    
    private static int LevenshteinDistance(string s, string t) {
        // Special cases
        if (s == t) return 0;
        if (s.Length == 0) return t.Length;
        if (t.Length == 0) return s.Length;
        // Initialize the distance matrix
        int[][] distance = new int[s.Length + 1][];
        for (int index = 0; index < s.Length + 1; index++)
        {
            distance[index] = new int[t.Length + 1];
        }

        for (int i = 0; i <= s.Length; i++) distance[i][0] = i;
        for (int j = 0; j <= t.Length; j++) distance[0][j] = j;
        // Calculate the distance
        for (int i = 1; i <= s.Length; i++) {
            for (int j = 1; j <= t.Length; j++) {
                int cost = (s[i - 1] == t[j - 1]) ? 0 : 1;
                distance[i][j] = Math.Min(Math.Min(distance[i - 1][j] + 1, distance[i][j - 1] + 1), distance[i - 1][j - 1] + cost);
            }
        }
        // Return the distance
        return distance[s.Length][t.Length];
    }
    
    public static Dictionary<DecorationCategory, string> CategoryNames = new()
    {
        { DecorationCategory.Animals, "Animals" },
        { DecorationCategory.Appliances, "Appliances" },
        { DecorationCategory.Beds, "Beds & Hammocks" },
        { DecorationCategory.Bookcases, "Bookcases" },
        { DecorationCategory.Buildings, "Buildings & Bridges" },
        { DecorationCategory.Clutter, "Clutter" },
        { DecorationCategory.CraftingTables, "Crafting Tables" },
        { DecorationCategory.DLC, "DLC Items" },
        { DecorationCategory.Fences, "Fences" },
        { DecorationCategory.FloorTiles, "Floor tiles" },
        { DecorationCategory.Foliage, "Foliage <size=75%><color=orange>(experimental)</color></size>" },
        { DecorationCategory.Halloween, "Halloween themed" },
        { DecorationCategory.HutchesLockers, "Hutches & Lockers" },
        { DecorationCategory.Instruments, "Instruments" },
        { DecorationCategory.Lighting, "Lighting" },
        { DecorationCategory.Mailboxes, "Mailboxes" },
        { DecorationCategory.MiscDecor, "Miscellaneous" },
        { DecorationCategory.Paintings, "Paintings" },
        { DecorationCategory.Pets, "Pets" },
        { DecorationCategory.Plants, "Plants" },
        { DecorationCategory.PetItems, "Pet items" },
        { DecorationCategory.Plushies, "Plushies" },
        { DecorationCategory.Rocks, "Rocks <size=75%><color=orange>(experimental)</color></size>" },
        { DecorationCategory.Rugs, "Rugs/Mats" },
        { DecorationCategory.Scarecrows, "Scarecrows" },
        { DecorationCategory.Seating, "Seating" },
        { DecorationCategory.SellingPortals, "Selling Portals" },
        { DecorationCategory.Statues, "Statues" },
        { DecorationCategory.Storage, "Storage" },
        { DecorationCategory.Surfaces, "Tables & Surfaces" },
        { DecorationCategory.WallDisplays, "Wall displays" },
        { DecorationCategory.Wallpaper, "Wallpaper" },
        { DecorationCategory.Windows, "Windows" },
        { DecorationCategory.Winter, "Winter themed" },
    };
    
    public static Dictionary<DecorationCategory, List<int>> Categories = new()
    {
        {
            DecorationCategory.Appliances, new List<int>()
            {
                ItemID.IndustrialCookingStove,
                ItemID.StoneOven,
                ItemID.DemonDramaTV,
                ItemID.RetroCarnivalTV,
                ItemID.RetroTV,
                ItemID.StaticTV,
                ItemID.Boiler
            }
        },
        {
            DecorationCategory.Beds, new List<int>()
            {
                ItemID.BirthdayBed,
                ItemID.SpiritPetalBed,
                ItemID.CyberpopBed,
                ItemID.RocknRollBed,
                ItemID.SpookyBed,
                ItemID.Bed,
                ItemID.BlueBed,
                ItemID.YellowBed,
                ItemID.NelvariTreehouseBed,
                ItemID.SlimeBed,
                ItemID.NiceDoubleBed,
                ItemID.BunnyBed,
                ItemID.IceCreamBed,
                ItemID.CloudBed,
                ItemID.ElvenLeafBed,
                ItemID.WithergateBed,
                ItemID.MonsterMouthBed,
                ItemID.PumpkinBed,
                ItemID.GoldBed,
                ItemID.BeachChairBed,
                ItemID.HolidayBed,
                ItemID.GloriteBed,
                ItemID.OrangeSliceBed,
                ItemID.SnaccoonBed,
                ItemID.WitchBed,
                ItemID.RegalBedCanopy,
                ItemID.VineStrungHammock,
                ItemID.BeachHammock,
                ItemID.PirateBed,
                ItemID.PirateHammock,
                ItemID.SeasideBed,
                ItemID.MushroomBed
            }
        },
        {
            DecorationCategory.Bookcases, new List<int>()
            {
                ItemID.CollectorsShelf,
                ItemID.NiceBookshelf,
                ItemID.SmallMysticsBookshelf,
                ItemID.ElvenLeafWallBookshelf,
                ItemID.CloudWallShelf,
                ItemID.IceCreamWallShelf,
                ItemID.OrangeSliceBookshelf,
                ItemID.MysticsBookshelf,
                ItemID.ClassicBookshelf,
                ItemID.LargeBookshelf,
                ItemID.PurpleBookStack,
                ItemID.Magazines,
                ItemID.SmallWoodenBookshelf,
            }
        },
        {
            DecorationCategory.HutchesLockers, new List<int>()
            {
                ItemID.GothicHutch,
                ItemID.ClassicHutch,
                ItemID.BlueLockers,
                ItemID.GreenElvenHutch,
            }
        },       
        {
            DecorationCategory.Instruments, new List<int>()
            {
                ItemID.RedElectricGuitar,
                ItemID.PurpleElectricGuitar,
                ItemID.BlueElectricGuitar,
                ItemID.AcousticGuitar,
                ItemID.OrchestralBass,
                ItemID.Harp,
                ItemID.GoldPiano,
                ItemID.Piano,
                ItemID.DrumSet,
                ItemID.Amp,
            }
        },        
        {
            DecorationCategory.Paintings, new List<int>()
            {
                ItemID.PeachPainting,
                ItemID.RedBarnPainting,
                ItemID.SunsetSmallPainting,
                ItemID.SunnyDaySmallPainting,
                ItemID.NightSmallPainting,
                ItemID.SmallPonyPainting,
                ItemID.MoodyFlowerPainting,
                ItemID.SwirlyNightPainting,
                ItemID.WildflowersPainting,
                ItemID.OrganicPainting,
                ItemID.GeodePainting,
                ItemID.SpookyPainting,
                ItemID.DreamyPainting,
                ItemID.BunnyCarrotPainting,
                ItemID.PeacefulWaterfallPainting,
                ItemID.MeatloafPainting,
                ItemID.WildMushroomsPainting,
                ItemID.BlackCatPainting,
                ItemID.ElegantVanityPainting,
                ItemID.TreeOvalPainting,
                ItemID.CityscapePainting,
                ItemID.EasternLandscapePainting,
                ItemID.SpiderwebPainting,
                ItemID.EasternDragonPainting,
                ItemID.PaintersDesignEasel,
                ItemID.IslandBreezePainting,
                ItemID.RosePaintingEasel,
                ItemID.SnaccoonPoster,
            }
        },        
        {
            DecorationCategory.Plants, new List<int>()
            {
                ItemID.YoungBonsai,
                ItemID.GlowingFlowerLights,
                ItemID.LuminesentPumpkin,
                ItemID.WitchsMoon,
                ItemID.ShimmerLeafPlant,
                ItemID.ShySnakePlant,
                ItemID.BroadLeafPlant,
                ItemID.HangingPothosPlant,
                ItemID.PottedBushPlant,
                ItemID.PottedFieldcress,
                ItemID.DracaenaPlant,
                ItemID.BlueHibiscusPlanter,
                ItemID.KittyCactus,
                ItemID.CactusPlant,
                ItemID.ZenPlant,
                ItemID.OshoPlant,
                ItemID.SweetheartPlant,
                ItemID.ZanderPlant,                
                ItemID.CrescentPlant,
                ItemID.PricklyDemonPlant,
                ItemID.SassyPlant,
                ItemID.PlantRack,
                ItemID.BabySproutPlant,
                ItemID.YellowFlower,
                ItemID.BlueRoseBouquet,
                ItemID.RedRoseBouquet,
                ItemID.BigLeafyPlant,
                ItemID.TallPlant,
                ItemID.SmallPottedBush,
                ItemID.BarrelOfRedFlowers,
                ItemID.BarrelofPurpleFlowers,
                ItemID.SmallSunflower,
                ItemID.LargeSunflower,
                ItemID.GiantSunflowers,
                ItemID.ButterflyStatueA,
                ItemID.RedRoseVase,
                ItemID.YellowFlower,
                ItemID.HangingWallPlant,
                ItemID.AloeVeraPlant,
                ItemID.CatEyeFlower,
                ItemID.BonsaiPlant,
                ItemID.DindleWeedPlant,
                ItemID.LuckyBambooPlant,
                ItemID.FiddleLeafFern,
                ItemID.HeartLeafPlant,
                ItemID.LushLeafPlant,
                ItemID.PinkLotusFlower,
                ItemID.PottedDesertFern,
                ItemID.PottedSweetGrassBush,
                ItemID.SagemaryPlant,
                ItemID.SproutingPlant,
                ItemID.StandingLeafDecor,
                ItemID.TerracottaPot,
                ItemID.TwinLeafPlant,
            }
        },        
        {
            DecorationCategory.WallDisplays, new List<int>()
            {
                ItemID.NeonSign,
                ItemID.MiyeonsAmateurPainting,
                ItemID.ElvenLoreTapestry,
                ItemID.WallHangingNecklace,
                ItemID.WatercolorTigerWallScroll,
                ItemID.HangingShortsword,
                ItemID.GreatArmyGuardBanner,
                ItemID.MoontouchedMirror,
                ItemID.WoodblockPrintedScroll,
                ItemID.GlowingFlowerLights,
                ItemID.DonovanTownFlag,
                ItemID.WallMountedSword,
                ItemID.BunnyPoster,
                ItemID.SmallPotionPoster,
                ItemID.CarnivalFlier,
                ItemID.ButterflyWallDisplay,
                ItemID.MetalSunWallPlaque,
                ItemID.StreetSignCollage,
                ItemID.HangingWallVinyl,
                ItemID.RetroPenguinRecordCover,
                ItemID.FauxUnicornWallMount,
                ItemID.FauxDragonWallMount,
                ItemID.RockinPoster,
                ItemID.JamminPoster,
                ItemID.BatPoster,
                ItemID.MoonBanner,
                ItemID.BatStreamer,
                ItemID.MysticEyeBanner,
                ItemID.GlowintheDarkStars,
                ItemID.FortuneTellerPoster,
                ItemID.CuckooWallClock,
                ItemID.HangingHorseshoe,
                ItemID.WallMountedSurfboard,
                ItemID.TargetPracticePaper,
                ItemID.WallIvy,
                ItemID.YellowWallFlags,
                ItemID.GoldenWindChimes,
                ItemID.RainbowPoster,
                ItemID.HerbalistPoster,
                ItemID.HangingPothosPlant,
                ItemID.WallCalendar,
                ItemID.KnightsWallShield,
                ItemID.WallCalendar,
                ItemID.DangerPoster,
                ItemID.NoSailingPoster,
                ItemID.RocknRollBlackGuitar,
                ItemID.RocknRollRedGuitar,
                ItemID.RocknRollGoldRecordAward,
            }
        },        
        {
            DecorationCategory.Statues, new List<int>()
            {
                ItemID.PrinceDariusBust,
                ItemID.GoldLionStatue,
                ItemID.BatMonsterStatue,
                ItemID.SquidMonsterStatue,
                ItemID.FerrisWheelMiniatureModel,
                ItemID.TailorStoreModel,
                ItemID.GoldColumn,
                ItemID.RoyalBlackColumn,
                ItemID.SmallWhiteColumn,
                ItemID.SmallBlackColumn,
                ItemID.VineWrappedColumn,
                ItemID.WoodenChickenSculpture,
                ItemID.BlueWoodenAbstractSculpture,
                ItemID.DynusVictoryTrophy,
                ItemID.GemTrophy,
                ItemID.NelVariManaInfuser,
                ItemID.CombatTrophy,
                ItemID.ExplorersTrophy,
                ItemID.FishingTrophy,
            }
        },
        {
            DecorationCategory.MiscDecor, new List<int>()
            {
                ItemID.GiantGoldenTimeTurner,
                ItemID.GoldenSandCastle,
                ItemID.GoldenGlassStatue,
                ItemID.EntertainmentBar,
                ItemID.NelVarianTranslationTexts,
                ItemID.HandCarvedSquirrelStatue,
                ItemID.EnchantedPinwheel,
                ItemID.HonorificKatana,
                ItemID.AngelicIncense,
                ItemID.MoontouchedFountain,
                ItemID.ConjuredBrazier,
                ItemID.DeliciousBreadDisplay,
                ItemID.CatScratchingPost,
                ItemID.SoggySandcastle,
                ItemID.TireChair,
                ItemID.WitherknightStatue,
                ItemID.GoldenHarp,
                ItemID.ElegantBass,
                ItemID.CyberpopGlobe,
                ItemID.CyberpopArcCapacitor,
                ItemID.CyberpopRecordPlayer,
                ItemID.CyberpopThrone,
                ItemID.CyberpopBicycle,
                ItemID.CyberpopHoverBike,
                ItemID.CyberpopMotorcycle,
                ItemID.RocknRollBlackGuitar,
                ItemID.RocknRollRedGuitar,
                ItemID.RocknRollAmp,
                ItemID.MushroomCoatRack,
                ItemID.MagazineStand,
                ItemID.GrandfatherClock,
                ItemID.FarmBarrel,
                ItemID.FarmChest,
                ItemID.FarmWateringCan,
                ItemID.HaySack,
                ItemID.LargeSack,
                ItemID.SmallSack,
                ItemID.Pitchfork,
                ItemID.SackOfBeans,
                ItemID.SackOfGrains,
                ItemID.SpareWoodenWheel,
                ItemID.WaterTrough,
                ItemID.BucketOfWater,
                ItemID.BlueHibiscusPlanter,
                ItemID.SteppingStones,
                ItemID.ArrowStorageBin,
                ItemID.CrateofFabrics,
                ItemID.CrateofScrolls,
                ItemID.ElvenSewingMachine,
                ItemID.CrateofToys,
                ItemID.CrateofClothes,
                ItemID.MovingBox,
                ItemID.SandCastle,
                ItemID.SandwichSign,
                ItemID.ShippingBox,
                ItemID.SmallBlueCooler,
                ItemID.WoodenBarrel,
                ItemID.WoodenMusicStand,
                ItemID.NelVariBalloons,
                ItemID.RosePaintingEasel,
                ItemID.TrellisPlanter,
                ItemID.WoodenStandingMirror,
                ItemID.TeaAltar,
                ItemID.WoodenWindmill,
                ItemID.BlackTire,
                ItemID.GumballMachine,
                ItemID.SlotMachine,
                ItemID.TrampolineShroom,
                ItemID.ChessBoard,
                ItemID.WalkwayClosedSign,
                ItemID.CloakRack,
                ItemID.WoodenLadder,
                ItemID.BarnBarrel,
                ItemID.SweepingBroom,
                ItemID.BeachBall,
                ItemID.BarrelOfSwords,
                ItemID.WeaponsRack,
                ItemID.EpicArmorStand,
                ItemID.Cauldron,
                ItemID.PlainPumpkin,
                ItemID.WitchPumpkin,
                ItemID.MonstrousPumpkin,
                ItemID.PumpkinCarriage,
                ItemID.GoldRecordPlayer,
                ItemID.RecordPlayer,
                ItemID.TrainingDummy,
                ItemID.PaintersDesignEasel,
                ItemID.WoodenPullCart,
                ItemID.SmallFishingNet,
                ItemID.WishingWell,
                ItemID.LargeFishingNet,
                ItemID.FeedingStation,
                ItemID.AutomaticFeeder,
                ItemID.BrewingCauldron,
                ItemID.WithergateWaterWell,
                ItemID.SmallAquarium,
                //ItemID.AnimalFeeder,
                ItemID.CarnivalBalloons,
                ItemID.WithergateBalloons,
                ItemID.PurpleStump,
                ItemID.CrateofTentacles,
                ItemID.ToyVendingMachine,
                ItemID.CrateofMushrooms,
                ItemID.FreshBasketofGreens,
                ItemID.BeachCooler,
                ItemID.SurfboardDisplay,
                ItemID.MetalStandingMirror,
                ItemID.LargeBallsofYarn,
                ItemID.LongWallMirror,
                ItemID.AutomaticCollector,
                ItemID.MetalBucket,
                ItemID.WoolCrate,
                ItemID.SackofOats,
                ItemID.SmallGroundHay,
                ItemID.LargeGroundHay,
                ItemID.FloralLadder,
                ItemID.HayFilledWheelBarrow,
                ItemID.OrangesFilledWheelbarrow,
                ItemID.StandeeFilledHay,
                ItemID.SpringAquarium,
                ItemID.SummerAquarium,
                ItemID.FallAquarium,
                ItemID.WinterAquarium,
                ItemID.NelVariAquarium,
                ItemID.WithergateAquarium,
                ItemID.CrateOfApples,
                ItemID.EmptyCrate,
                ItemID.EmptyWheelbarrow,
                ItemID.FlowerPlanter,
                ItemID.WithergateBarnArch,
                ItemID.IronFeedingTrough,
                ItemID.RedOilDrum,
                ItemID.GreenOilDrum,
                ItemID.BlueOilDrum,
                ItemID.BarrelCluster,
                ItemID.WormInfestedApples,
                ItemID.ThornyPlanter,
                ItemID.BiteyPlanter,
                ItemID.PumpkinFilledWheelbarrow,
                ItemID.OldScythe,
                ItemID.EmptyPlanter,
                ItemID.TShapedPipe,
                ItemID.ThickGreenPipe,
                ItemID.LineofPipes,
                ItemID.NelVariBarnArch,
                ItemID.HangingSpoolofRope,
                ItemID.Rake,
                ItemID.PirateAnchor,
                ItemID.PirateCannon,
                ItemID.SpookyPumpkinCauldron,
                ItemID.SpookyStackofPumpkins,
            }
        },
        {
            DecorationCategory.Winter, new List<int>()
            {
                ItemID.HolidayWreath,
                ItemID.WreathStand,
                ItemID.HolidayTree,
                ItemID.SnowBuddy,
                ItemID.PileOfPresents,
                ItemID.YuleLogs,
                ItemID.HangingBells,
                ItemID.BowBell,
                ItemID.ClassicBell,
                ItemID.ThinBell,
                ItemID.LongBells,
                ItemID.BlueHolidayStocking,
                ItemID.GreenStocking,
                ItemID.BlueStocking,
                ItemID.RedStocking,
                ItemID.StripedYellowStocking,
                ItemID.StripedBlueStocking,
                ItemID.StripedRedStocking,
                ItemID.RedGreenStocking,
                ItemID.SnowyStocking,
                ItemID.PolkaDotStocking,
                ItemID.OrnamentStreamers,
                ItemID.HolidayStringLights,
                ItemID.HolidayStringLightsFence,
                ItemID.CrackedReindeerIceSculpture,
                ItemID.ReindeerIceSculpture,
                ItemID.SnowGlobeIceSculpture,
                ItemID.AngelWingIceSculpture,
                ItemID.SwanIceSculpture,
                ItemID.PeacockIceSculpture,
                ItemID.DragonIceSculpture,
                ItemID.StackofPresents,
                ItemID.FestiveTree,
                ItemID.FestiveWallBanners,
                ItemID.WinterSellingPortal,
            }
        },                   
        {
            DecorationCategory.Halloween, new List<int>()
            {
                
                ItemID.WitchBed,
                ItemID.WitchWardrobe,
                ItemID.WitchCouch,
                ItemID.WitchEndTable,
                ItemID.WitchTable,
                ItemID.WitchChair,
                ItemID.WitchLamp,
                ItemID.WitchRug,
                ItemID.CauldronofMysteriousOrangeLiquid,
                ItemID.CauldronOfMysteriousGreenLiquid,
                ItemID.StandingCoffin,
                ItemID.FakeEyeball,
                ItemID.PlainPumpkin,
                ItemID.WitchPumpkin,
                ItemID.MonstrousPumpkin,
                ItemID.PumpkinCarriage,
                ItemID.VoodooDoll,
                ItemID.StoneMortarandPestle,
                ItemID.SmallVial,
                ItemID.PoisonedApples,
                ItemID.EmptyJar,
                ItemID.PotionJar,
                ItemID.HalloweenFence,
                ItemID.PirateWardrobe,
                ItemID.SpookyRug,
                ItemID.SpookyBed,
                ItemID.SpookyWardrobe,
                ItemID.SpookyCouch,
                ItemID.SpookyChair,
                ItemID.SpookyEndTable,
                ItemID.SpookyTable,
                ItemID.SpookyPumpkinCauldron,
                ItemID.SpookyStackofPumpkins,
                ItemID.WitchsMoon,
                ItemID.HalloweenFence,
            }
        },                   
        {
            DecorationCategory.Lighting, new List<int>()
            {
                ItemID.BirthdayLamp,
                ItemID.ConjuredBrazier,
                ItemID.GlowingFlowerLights,
                ItemID.LuminesentPumpkin,
                ItemID.WitchsMoon,
                ItemID.SpiritPetalLamp,
                ItemID.RocknRollLamp,
                ItemID.SeasideLamp,
                ItemID.CandyMushroomLight,
                ItemID.SmallStoneFireplace,
                ItemID.StoneLantern,
                ItemID.MushroomLampPost,
                ItemID.MushroomStandingLamp,
                ItemID.BabyMushroomLight,
                ItemID.NiceWoodenLamp,
                ItemID.WhiteTableLamp,
                ItemID.RedTableLamp,
                ItemID.GreenTableLamp,
                ItemID.BlueTableLamp,
                ItemID.PurpleTableLamp,
                ItemID.WhiteFloorLamp,
                ItemID.RedBankersLight,
                ItemID.OrangeSliceLamp,
                ItemID.ElvenLeafLamp,
                ItemID.IceCreamLamp,
                ItemID.RainbowCloudWallLamp,
                ItemID.WithergateLamp,
                ItemID.BunnyLamp,
                ItemID.PumpkinLamp,
                ItemID.WitchLamp,
                ItemID.BigJackOLamp,
                ItemID.FlamingoLamp,
                ItemID.BentWithergateLamp,
                ItemID.LargeWithergateLamp,
                ItemID.MediumWithergateLamp,
                ItemID.SmallWithergateLamp,
                ItemID.Candle,
                ItemID.LavenderCandle,
                ItemID.BookCandles,
                ItemID.Candelabra,
                ItemID.TallCandelabra,
                ItemID.WickedCandelabra,
                ItemID.WoodenTorch,
                ItemID.Lantern,
                ItemID.DarkGreyTableLantern,
                ItemID.FloatingEnchantedLantern,
                ItemID.OrangeBatWallLantern,
                ItemID.BlueSkullWallLantern,
                ItemID.PurpleEyeWallLantern,
                ItemID.WickedWallLantern,
                ItemID.SillyChickenLantern,
                ItemID.ChickenLantern,
                ItemID.RoosterLantern,
                ItemID.ChickLantern,
                ItemID.BoxPaperLantern,
                ItemID.HourglassPaperLantern,
                ItemID.TaperedPaperLantern,
                ItemID.BlueStringLights,
                ItemID.PurpleStringLights,
                ItemID.RoundStringLights,
                ItemID.HolidayStringLights,
                ItemID.PaperLanternStrand,
                ItemID.BatStreamer,
                ItemID.EyeballStreamer,
                ItemID.BasicFireplace,
                ItemID.SunHavenFireplace,
                ItemID.RoyalWithergateFireplace,
                ItemID.MonsterFireplace,
                ItemID.GoldFireplace,
                ItemID.RusticBrickFireplace,
                ItemID.RedNeonDoorLight,
                ItemID.GreenNeonLight,
                ItemID.NeonBat,
                ItemID.CampFire,
                ItemID.BlueCampfire,
                ItemID.MysticalFirePit,
                ItemID.LEDBatBanner,
                ItemID.LEDSkullBanner,
                ItemID.TrafficLight,
                ItemID.DoubleLampPost,
                ItemID.NeonDragonHeadLight,
                ItemID.GloriteLamp,
                ItemID.SpookyLampPost,
            }
        },                   
        {
            DecorationCategory.PetItems, new List<int>()
            {
                ItemID.BluePetHouse,
                ItemID.BrownPetHouse,
                ItemID.PinkPetHouse,
                ItemID.PurplePetHouse,
                ItemID.RedPetHouse,
                ItemID.GoldPetHouse,
                ItemID.PetCarrier,
                ItemID.CrateOfFetchBalls,
                ItemID.PetWaterBowl,
                ItemID.ChewyRopePetToy,
                ItemID.WoodenCatTree,
                ItemID.BasketOfYarnBalls,
                ItemID.WhiteSleepyCat,
                ItemID.MouseBuddyDecoration,
                ItemID.FroggyBuddy,
                ItemID.InsectBuddy,
                ItemID.LushBirdBath,
                ItemID.BagofKibble,
            }
        },
        {
            DecorationCategory.Plushies, new List<int>()
            {
                ItemID.BabyPandaPlushie,
                ItemID.BatPlushie,
                ItemID.BeePlushie,
                ItemID.BlackCatPlushie,
                ItemID.DoubleHeadedCatPlushie,
                ItemID.LuckyCatPlushie,
                ItemID.PinkCatPlushie,
                ItemID.CobraPlushie,
                ItemID.CowPlushie,
                ItemID.DogPlushie,
                ItemID.BlueElephantPlushie,
                ItemID.PinkElephantPlushie,
                ItemID.LadybugPlushie,
                ItemID.OctopusPlushie,
                ItemID.PenguinPlushie,
                ItemID.SnailPlushie,
                ItemID.SpiderPlushie,
                ItemID.SquidPlushie,
                ItemID.TriceratopsPlushie,
                ItemID.TurtlePlushie,
                ItemID.GiantPinkTeddyPlushie,
                ItemID.GiantPurpleTeddyPlushie,
                ItemID.GiantTeddyPlushie,
                ItemID.GiantBlueBunnyPlushie,
                ItemID.GiantPinkBunnyPlushie,
                ItemID.DynusPlushie,
                ItemID.SnaccoonPlushie,
                ItemID.AnglerSnaccoonPlush,
                ItemID.BeachSnaccoonPlush,
                ItemID.BunnySnaccoonPlush,
                ItemID.CamperSnaccoonPlush,
                ItemID.CowboySnaccoonPlush,
                ItemID.ExplorerSnaccoonPlush,
                ItemID.FarmerSnaccoonPlush,
                ItemID.GhostSnaccoonPlush,
                ItemID.MinerSnaccoonPlush,
                ItemID.NelVariSnaccoonPlush,
                ItemID.PajamaSnaccoonPlush,
                ItemID.ScarfSnaccoonPlush,
                ItemID.VampireSnaccoonPlush,
                ItemID.WithergateSnaccoonPlush,
                ItemID.BabyEliosPlushie,
                ItemID.CharonPlushie,
                ItemID.ChubbyDynusPlushie,
                ItemID.ScuzzyPlushie,
                ItemID.SlobertPlushie,
                ItemID.LimitedEditionDynusPlushie,
                ItemID.DogPlushie,
                ItemID.YearoftheDragonPlush,
                ItemID.YearoftheHorsePlush,
                ItemID.YearoftheMonkeyPlush,
                ItemID.YearoftheOxPlush,
                ItemID.PigletPlushie,
                ItemID.YearoftheRabbitPlush,
                ItemID.YearoftheRamPlush,
                ItemID.YearoftheRatPlush,
                ItemID.YearoftheRoosterPlush,
                ItemID.YearoftheSnakePlush,
                ItemID.YearoftheTigerPlush,
                ItemID.AppleandWormPlushie,
                ItemID.CandyCornPlushie,
                ItemID.CandyPlushie,
                ItemID.IceCreamPlushie,
                ItemID.PumpkinPlushie,
                ItemID.SprinklesPlushie,
                ItemID.AlienPlushie,
                ItemID.CuteMonsterPlushie,
                ItemID.GhostPlushie,
                ItemID.ShootingStarPlushie,
                ItemID.DonutSlime,
                ItemID.YearoftheDogPlush,
                ItemID.YearofthePigPlush,
            }
        },                   
        {
            DecorationCategory.Rugs, new List<int>()
            {
                ItemID.ConfettiRug,
                ItemID.SpiritPetalRug,
                ItemID.CyberpopRug,
                ItemID.RocknRollBlackRug,
                ItemID.RocknRollRedRug,
                ItemID.SpookyRug,
                ItemID.BlueSeasideShellRug,
                ItemID.BlueSeasideStarfishRug,
                ItemID.PinkSeasideShellRug,
                ItemID.PinkSeasideStarfishRug,
                ItemID.BlueBohoRoundRug,
                ItemID.BlueCarpet,
                ItemID.BlueFringeCarpet,
                ItemID.GreenPetalRug,
                ItemID.FluffyAmberDoormat,
                ItemID.FluffyRedDoormat,
                ItemID.MeowWelcomeMat,
                ItemID.NauticalDoormat,
                ItemID.WoofWelcomeMat,
                ItemID.BlueBeachTowel,
                ItemID.GreenStripedBeachTowel,
                ItemID.OrangeStripedBeachTowel,
                ItemID.PinkBeachTowel,
                ItemID.PurpleBeachTowel,
                ItemID.PurpleStripedBeachTowel,
                ItemID.TurquoiseDoormat,
                ItemID.YellowDoormat,
                ItemID.SunflowerRug,
                ItemID.BohoRoundRug,
                ItemID.PurpleBohoRug,
                ItemID.TealAndYellowOrnateRug,
                ItemID.BrownOrnateOvalRug,
                ItemID.BlackOrnateOvalRug,
                ItemID.GoldOrnateRug,
                ItemID.PinkOrnateOvalRug,
                ItemID.NightskyRug,
                ItemID.JackORug,
                ItemID.RedFlowerRug,
                ItemID.YellowFlowerRug,
                ItemID.OrangeSliceRug,
                ItemID.SunHavenRug,
                ItemID.WithergateApartmentRug,
                ItemID.NelvariTreehouseRug,
                ItemID.FancyPurpleandBlackRug,
                ItemID.BorderedCrimsonRug,
                ItemID.FancyGoldandGreenRug,
                ItemID.LongFringeBlackRug,
                ItemID.BlueVelvetFringeRug,
                ItemID.PinkVelvetFringeRug,
                ItemID.LongBeigeRug,
                ItemID.LongGreenRug,
                ItemID.LongPurpleRug,
                ItemID.LongRedRug,
                ItemID.LongRedDesertRug,
                ItemID.BlueRegalRug,
                ItemID.BunnyMat,
                ItemID.WithergateMat,
                ItemID.MarigoldLeafRug,
                ItemID.WovenPurpleRug,
                ItemID.WovenYellowRug,
                ItemID.LargeWhiteFluffyRug,
                ItemID.LargeFluffyAmberRug,
                ItemID.LargeFluffyNavyRug,
                ItemID.LargeFluffyRedRug,
                ItemID.OrnateSquareBlueRug,
                ItemID.RoyalWithergateRug,
                ItemID.BeachRug,
                ItemID.FancyMagentaRug,
                ItemID.PinkShaggyRug,
                ItemID.YellowShaggyRug,
                ItemID.FluffyRug,
                ItemID.BlueRug,
                ItemID.LightBlueRug,
                ItemID.RedRug,
                ItemID.BlackRug,
                ItemID.FauxTigerRug,
                ItemID.IceCreamRug,
                ItemID.ElvenLeafRug,
                ItemID.PurpleBatRug,
                ItemID.PumpkinRug,
                ItemID.GloriteRug,
                ItemID.FlamingoRug,
                ItemID.WitchRug,
                ItemID.SnowflakeRug,
                ItemID.RedPetalRug,
                ItemID.PurplePetalRug,
                ItemID.PurpleSemiRoundRug,
                ItemID.LargeFluffyPurpleRug,
                ItemID.PurpleFluffyRug,
                ItemID.PawPrintDoormat,
                ItemID.RedCarpet,
                ItemID.RedFringeCarpet,
                ItemID.MushroomCarpet,
            }
        },
        {
            DecorationCategory.Seating, new List<int>()
            {
                ItemID.BirthdayCouch,
                ItemID.BirthdayChair,
                ItemID.NatureChair,
                ItemID.SpiritPetalCouch,
                ItemID.SpiritPetalChair,
                ItemID.CyberpopStudentChair,
                ItemID.CyberpopCouch,
                ItemID.RocknRollCouch,
                ItemID.SpookyChair,
                ItemID.SpookyCouch,
                ItemID.SeasideChair,
                ItemID.ApplePillow,
                ItemID.BabyStool,
                ItemID.GreenWoodenBench,
                ItemID.GreenFloorCushion,
                ItemID.PurpleFloorCushion,
                ItemID.YellowFloorCushion,
                ItemID.WoodenStepStool,
                ItemID.BunnyChairL,
                ItemID.BunnyChairR,
                ItemID.BunnyChairUp,
                ItemID.PurpleCushionChairR,
                ItemID.RedCushionChairUp,
                ItemID.RedCushionChairL,
                ItemID.RedCushionChairR,
                ItemID.RockingChair,
                ItemID.WithergateChair,
                ItemID.NelvariTreehouseChair,
                ItemID.BasicWoodenChair,
                ItemID.BasicWoodenChairL,
                ItemID.BasicWoodenChairR,
                ItemID.ArchedWoodenChair,
                ItemID.BlackLeatherChairL,
                ItemID.BlueCushionChair,
                ItemID.PurpleCushionChair,
                ItemID.RedCushionChair,
                ItemID.FancyBlueDiningChair,
                ItemID.PumpkinChair,
                ItemID.MonsterMouthChair,
                ItemID.OrangeSliceChair,
                ItemID.ElvenLeafChair,
                ItemID.BunnyChair,
                ItemID.StarChair,
                ItemID.GloriteChair,
                ItemID.WithergateChair,
                ItemID.IceCreamChair,
                ItemID.SnaccoonChair,
                ItemID.BeachChair,
                ItemID.WitchChair,
                ItemID.PinkShellChair,
                ItemID.HolidayThrone,
                ItemID.PurpleCouchSeat,
                ItemID.TurquoiseCouchSeat,
                ItemID.GreenCouchSeat,
                ItemID.BlackCouchSeat,
                ItemID.GreenLeatherSideCouchSeat,
                ItemID.BlueLeatherSideCouchSeat,
                ItemID.BrownLeatherCouchSeat,
                ItemID.BrownGeoCouch,
                ItemID.EarthyStripedCouch,
                ItemID.GothicCouch,
                ItemID.YellowDeepCouch,
                ItemID.BlueVelvetCouch,
                ItemID.RedBurstCouch,
                ItemID.PurpleQuiltedSofa,
                ItemID.RedQuiltedCouch,
                ItemID.LightGrayDiamondCouch,
                ItemID.RedButterflyCouch,
                ItemID.NiceSofa,
                ItemID.GoldCouch,
                ItemID.BrownLeatherCouch,
                ItemID.OrangeSliceCouch,
                ItemID.BunnyCouch,
                ItemID.IceCreamCouch,
                ItemID.WithergateCouch,
                ItemID.CloudCouch,
                ItemID.ElvenLeafCouch,
                ItemID.SnaccoonCouch,
                ItemID.MonsterMouthCouch,
                ItemID.HolidayCouch,
                ItemID.CoolCatCouch,
                ItemID.WatermelonCouch,
                ItemID.BigRedComfyCouch,
                ItemID.LightGreenCouch,
                ItemID.EspressoCushionedCouch,
                ItemID.BlueCouchSeat,
                ItemID.BlackCouchSeat,
                ItemID.WoodenStool,
                ItemID.RedBarStool,
                ItemID.BlueFluffyStool,
                ItemID.BlueCushionStool,
                ItemID.PurpleCushionStool,
                ItemID.BrownLeatherStool,
                ItemID.ShinyLeatherRedStool,
                ItemID.ShinyLeatherOrangeStool,
                ItemID.ShinyLeatherGreenStool,
                ItemID.ShinyLeatherTurquoiseStool,
                ItemID.ShinyLeatherPurpleStool,
                ItemID.WoodenBench,
                ItemID.LongBlueWoodenBench,
                ItemID.LongPurpleWoodenBench,
                ItemID.BlueFloorCushion,
                ItemID.PurpleOttoman,
                ItemID.WithergateApartmentChair,
                ItemID.BlueCushionSideCouch,
                ItemID.ShinyLeatherYellowStool,
                ItemID.BlackCushionedCouch,
                ItemID.EmeraldChaiseCouch,
                ItemID.BeigeChaiseCouch,
                ItemID.PurpleLoveseat,
                ItemID.TealBubbleCouch,
                ItemID.PurpleCabrioleCouch,
                ItemID.MagentaChaiseCouch,
                ItemID.TealSectionalCouch,
                ItemID.GothicChaiseCouch,
                ItemID.PumpkinCouch,
                ItemID.PurpleWoodenChair,
                ItemID.PurpleRoundStool,
                ItemID.ShinyLeatherSageStool,
                ItemID.StumpStool,
                ItemID.TealCraftersStool,
                ItemID.PirateChair,
            }
        },          
        {
            DecorationCategory.Storage, new List<int>()
            {
                ItemID.BirthdayWardrobe,
                ItemID.SpiritPetalWardrobe,
                ItemID.CyberpopStudentChest,
                ItemID.CyberpopWardrobe,
                ItemID.RocknRollWardrobe,
                ItemID.SpookyWardrobe,
                ItemID.SeasideChest,
                ItemID.Chest,
                ItemID.WoodFlatheadChest,
                ItemID.RedFlatheadChest,
                ItemID.GoldChest,
                ItemID.NightSkyChest,
                ItemID.WoodenWardrobe,
                ItemID.BunnyWardrobe,
                ItemID.NiceWardrobe,
                ItemID.OrangeSliceWardrobe,
                ItemID.IceCreamWardrobe,
                ItemID.CloudWardrobe,
                ItemID.ElvenLeafWardrobe,
                ItemID.WithergateWardrobe,
                ItemID.HolidayWardrobe,
                ItemID.PumpkinWardrobe,
                ItemID.GloriteWardrobe,
                ItemID.CarvedElvenWardrobe,
                ItemID.MonsterMouthWardrobe,
                ItemID.SnaccoonWardrobe,
                ItemID.BeachWardrobe,
                ItemID.WitchWardrobe,
                ItemID.BasicFridge,
                ItemID.SunHavenFridge,
                ItemID.BlackFridge,
                ItemID.GoldFridge,
                ItemID.BunnyFridge,
                ItemID.ModestTealFridge,
                ItemID.PirateChest,
                ItemID.SeasideWardrobe,
            }
        },          
        { 
            DecorationCategory.Surfaces, new List<int>()
            {
                ItemID.BirthdayTable,
                ItemID.SpiritPetalEndTable,
                ItemID.SpiritPetalTable,
                ItemID.CyberpopDesk,
                ItemID.CyberpopTable,
                ItemID.RocknRollEndTable,
                ItemID.RocknRollTable,
                ItemID.SpookyEndTable,
                ItemID.SpookyTable,
                ItemID.MushroomTable,
                ItemID.MushroomEndTable,
                ItemID.SeasideTable,
                ItemID.SeasideEndTable,
                ItemID.CarvedElvenCoffeeTable,
                ItemID.CarvedElvenRoundTable,
                ItemID.PineDesk,
                ItemID.PinkMatDesk,
                ItemID.PinkPawTable,
                ItemID.SquareCoffeeTable,
                ItemID.BeachTable,
                ItemID.WoodenRoundTable,
                ItemID.DarkWoodenRoundTable,
                ItemID.BlueWoodenRoundTable,
                ItemID.RoundBlueWoodenCoffeeTable,
                ItemID.OrangeSliceTable,
                ItemID.BunnyTable,
                ItemID.WoodenTable,
                ItemID.WithergateApartmentTable,
                ItemID.CarvedElvenSquareTable,
                ItemID.CarvedElvenLongTable,
                ItemID.WoodenLongTable,
                ItemID.BlueWoodenLongTable,
                ItemID.CloudTable,
                ItemID.IceCreamTable,
                ItemID.WithergateTable,
                ItemID.PinkTableRunnerDiningTable,
                ItemID.BlueLinedWoodenTable,
                ItemID.LongWoodenDisplayTable,
                ItemID.SnaccoonTable,
                ItemID.HolidayTable,
                ItemID.BlueWoodenEndTable,
                ItemID.BaroqueEndTable,
                ItemID.BaroqueHalfMoonTable,
                ItemID.IceCreamEndTable,
                ItemID.BunnySideTable,
                ItemID.HolidayEndTable,
                ItemID.NiceWoodenNightStand,
                ItemID.OrangeSliceNightstand,
                ItemID.CloudNightstand,
                ItemID.ElvenLeafNightstand,
                ItemID.PumpkinNightstand,
                ItemID.PurpleNightstand,
                ItemID.SnaccoonNightstand,
                ItemID.WoodenCounter,
                ItemID.WithergateApartmentCounter,
                ItemID.CarvedElvenCounter,
                ItemID.CarvedElvenLCounter,
                ItemID.OakKitchenIsland,
                ItemID.OakKitchenCabinet,
                ItemID.MapleKitchenCabinet,
                ItemID.KitchenSinkCounter,
                ItemID.DarkTealSinkCounter,
                ItemID.OakKitchenSinkCounter,
                ItemID.RusticKitchenCounter,
                ItemID.SideDeskTable,
                ItemID.PicnicTable,
                ItemID.WithergatePicnicTable,
                ItemID.PurpleMatDesk,
                ItemID.Shelf,
                ItemID.WarmWoodenWallShelf,
                ItemID.PurpleWallShelf,
                ItemID.PoolTable,
                ItemID.BabyTable,
                ItemID.WithergateApartmentEndTable,
                ItemID.NeonPinkLDesk,
                ItemID.GloriteTable,
                ItemID.GloriteEndTable,
                ItemID.NelvariTreehouseWoodenSquareTable,
                ItemID.NelvariTreehouseCounter,
                ItemID.NelvariTreehouseSideTable,
                ItemID.FancyBlueDiningTable,
                ItemID.RoyalTable,
                ItemID.RoyalDesk,
                ItemID.BlueWoodenCounter,
                ItemID.BlueWoodenLTable,
                ItemID.MonsterMouthTable,
                ItemID.MonsterMouthEndTable,
                ItemID.PumpkinTable,
                ItemID.PurpleWoodenSquareDesk,
                ItemID.PrincessVanityTable,
                ItemID.BlueWoodenSquareTable,
                ItemID.InsigniaEmblemDesk,
                ItemID.LightGreenLinedWoodenTable,
                ItemID.GreenWoodenWallShelf,
                ItemID.LeafyCubby,
                ItemID.MahoganyCounter,
                ItemID.ClassicWoodenDresser,
                ItemID.PirateTable,
                ItemID.MushroomBookshelf
            }
        },
        {
            DecorationCategory.Clutter, new List<int>()
            {
                ItemID.PinataTeal,
                ItemID.PinataStriped,
                ItemID.PinataOrange,
                ItemID.PinataWatermelon,
                ItemID.PinataCarrot,
                ItemID.PinataBlue,
                ItemID.BirthdayPlaceSettings,
                ItemID.MedicalGradeMicroscope,
                ItemID.PersonalMedKit,
                ItemID.ModelTrainSet,
                ItemID.DelicateHammer,
                ItemID.AngelicFloralTeaPot,
                ItemID.FlamingBookofSpells,
                ItemID.AutoMixer,
                ItemID.KittysBirthdayDress,
                ItemID.SnakeStatue,
                ItemID.YoungBonsai,
                ItemID.DriedHerbs,
                ItemID.DiamondDisplay,
                ItemID.MiniDukeStatue,
                ItemID.SpiritOrb,
                ItemID.RedMushroomDecoration,
                ItemID.LightBrownMushroomDecoration,
                ItemID.MilkChurn,
                ItemID.TinBucket,
                ItemID.TrafficCone,
                ItemID.OldStrawHat,
                ItemID.JamJar,
                ItemID.VanillaMilkshake,
                ItemID.WideToothComb,
                ItemID.WoodenSpoon,
                ItemID.YellowPotwithBluePrint,
                ItemID.BookCollection,
                ItemID.ChooChooTrainToy,
                ItemID.UmbrellaStand,
                ItemID.LogPile,
                ItemID.BoxofBottles,
                ItemID.RackofVials,
                ItemID.RainbowJars,
                ItemID.SpireaFlowerBasket,
                ItemID.BlueSpoolofThread,
                ItemID.BrownScissors,
                ItemID.ClayVase,
                ItemID.DinnerPlate,
                ItemID.FirstAidKit,
                ItemID.FoldedLeafShirt,
                ItemID.GreenandBlueJars,
                ItemID.DeliciousDrink,
                ItemID.GreenElvenVase,
                ItemID.PinkElvenVase,
                ItemID.PurpleElvenVase,
                ItemID.RedElvenVase,
                ItemID.MaroonElvenVase,
                ItemID.GrayElvenVase,
                ItemID.BlueElvenVase,
                ItemID.CobaltElvenVase,
                ItemID.EarthyElvenVase,
                ItemID.ClayPot,
                ItemID.VioletVase,
                ItemID.RedRoseVase,
                ItemID.GoldSnakeVase,
                ItemID.FireflyJar,
                ItemID.BlueAndGreenBottles,
                ItemID.RedAndOrangeBottles,
                ItemID.RedGemBottle,
                ItemID.GreenGemBottle,
                ItemID.MantelClock,
                ItemID.RoundWallClock,
                ItemID.HangingPans,
                ItemID.CuttingBoardwithLemon,
                ItemID.LargeKettlePot,
                ItemID.MetalCoffeePot,
                ItemID.GlassCoffeePot,
                ItemID.PurpleTeapot,
                ItemID.CoffeeMug,
                ItemID.ShinyYellowMug,
                ItemID.RedMug,
                ItemID.BigDeliciousCake,
                ItemID.BlackForestCakeSlice,
                ItemID.HalfLoafofBread,
                ItemID.CanofBeans,
                ItemID.JarofCherries,
                ItemID.SackofSugar,
                ItemID.BlockofCheese,
                ItemID.BasketofEggs,
                ItemID.BasketofBuns,
                ItemID.CandyCorn,
                ItemID.BreadBasket,
                ItemID.Breadsticks,
                ItemID.SmallRedVanityMirror,
                ItemID.MoonMirror,
                ItemID.BattyBoxes,
                ItemID.TrashCan,
                ItemID.ThreeDrawerCrate,
                ItemID.RedCrateOfRecords,
                ItemID.WoodenCrateOfRecords,
                ItemID.PurpleQuill,
                ItemID.MysticOrb,
                ItemID.BatTeaSet,
                ItemID.FidgetSpinner,
                ItemID.FingerTraps,
                ItemID.PuzzleCube,
                ItemID.PiggyBank,
                ItemID.FuzzyDice,
                ItemID.CozyFireLogs,
                ItemID.AstrologicalGlobe,
                ItemID.JackOStack,
                ItemID.SmallHayPile,
                ItemID.LargeHayPile,
                ItemID.CrumpledPaper,
                ItemID.MysteriousBlackBottle,
                ItemID.PumpkinTrio,
                ItemID.MagicWandHolder,
                ItemID.PawnChessPiece,
                ItemID.CandyBowls,
                ItemID.BabyPumpkinStack,
                ItemID.GhostInPumpkin,
                ItemID.GrapeSodaPop,
                ItemID.SodaCan,
                ItemID.SliceofCherryPie,
                ItemID.PartyLeftovers,
                ItemID.RedHighHeels,
                ItemID.BrownSneakers,
                ItemID.CanofSardines,
                ItemID.CanofSoup,
                ItemID.CherryBowl,
                ItemID.CreamerPitcher,
                ItemID.FishBowl,
                ItemID.FoldedPolkaDotShirt,
                ItemID.GoldenGoblet,
                ItemID.GreenBookStack,
                ItemID.GreenHairbrush,
                ItemID.GreenSneakers,
                ItemID.KnifeBlock,
                ItemID.LoafofBread,
                ItemID.MilkCarton,
                ItemID.MortarAndPestle,
                ItemID.PendantNecklace,
                ItemID.PerfectRedTulip,
                ItemID.PerfectYellowTulip,
                ItemID.PerfumeBottle,
                ItemID.PinkHairbrush,
                ItemID.PinkWateringCan,
                ItemID.PurpleBowDecoration,
                ItemID.PurpleSneakers,
                ItemID.RedHandheldMirror,
                ItemID.RedTissueBox,
                ItemID.SackofCoffeeBeans,
                ItemID.SackofFlour,
                ItemID.SmallGreenPotion,
                ItemID.SoapBottle,
                ItemID.SoccerBall,
                ItemID.StackofLetters,
                ItemID.StrawberryandCreamCake,
                ItemID.GreenBook,
                ItemID.GreenGlazedPot,
                ItemID.GreenQuill,
                ItemID.GreenScissors,
                ItemID.GreenSpoolofThread,
                ItemID.HoneyPot,
                ItemID.LargePaintBrush,
                ItemID.LittleGreenVial,
                ItemID.PaintBrushCup,
                ItemID.PaperScroll,
                ItemID.PurpleBook,
                ItemID.PurpleJar,
                ItemID.RedandBlueBottles,
                ItemID.RedBookStack,
                ItemID.RedMixingPot,
                ItemID.TealBook,
                ItemID.WaterJug,
                ItemID.WoodenPaintPalette,
                ItemID.PirateTreasureMap,
                ItemID.PirateWoodPost,
            }
        },          
        {
            DecorationCategory.SellingPortals, new List<int>()
            {
                ItemID.SunHavenSellingPortal,
                ItemID.NelVariSellingPortal,
                ItemID.WithergateSellingPortal,
                ItemID.SpringSellingPortal,
                ItemID.SummerSellingPortal,
                ItemID.FallSellingPortal,
                ItemID.WinterSellingPortal,
                ItemID.LanternFestivalSellingPortal,
            }
        },          
        {
            DecorationCategory.Mailboxes, new List<int>()
            {
                ItemID.ClassicMailbox,
                ItemID.SmithedMailbox,
                ItemID.MoonMailbox,
                ItemID.BirdhouseMailbox,
                ItemID.OrangeTopMailbox,
                ItemID.FlowerMailbox,
                ItemID.PinkBunnyMailbox,
                ItemID.DemonMailbox,
                ItemID.MailboxDemolitionKit
            }
        },          
        {
            DecorationCategory.Windows, new List<int>()
            {
                ItemID.LargeWindow,
                ItemID.PinkStainedGlassWindow,
                ItemID.RedTWindow,
                ItemID.YellowTWindow,
                ItemID.BatWindow,
                ItemID.TallTreeWindow,
                ItemID.WideTreeWindow,
                ItemID.FlowerWindows,
                ItemID.RusticElegantWindow,
                ItemID.ElvenWindow,
                ItemID.FactoryArchedWindow,
                ItemID.SimpleFarmerWindow,
                ItemID.ElvenFactoryArchedWindow,
                ItemID.DoubleArchingWindow,
                ItemID.ElvenRuralWindow,
            }
        },          
        {
            DecorationCategory.Wallpaper, new List<int>()
            {
                ItemID.NightForestWallpaper,
                ItemID.SunriseForestWallpaper,
                ItemID.BasicWallpaper,
                ItemID.FlowerWallpaper,
                ItemID.WithergateWallpaper,
                ItemID.VintageWallpaper,
                ItemID.EarthyGridWallpaper,
                ItemID.PinkRosebudWallpaper,
                ItemID.PurpleGridWallpaper,
                ItemID.PurpleStripedWallpaper,
                ItemID.ParchmentWallpaper,
                ItemID.RetroStripedWallpaper,
                ItemID.BlueDiamondWallpaper,
                ItemID.BunnyWallpaper,
                ItemID.PurpleVintageWallpaper,
                ItemID.RedBrickWallpaper,
                ItemID.BrownBrickWallpaper,
                ItemID.NiceBlueWallpaper,
                ItemID.NiceGreenWallpaper,
                ItemID.NiceIvoryWallpaper,
                ItemID.NiceLightBlueWallpaper,
                ItemID.BlueStripedWallpaper,
                ItemID.WithergateRoyaltyWallpaper,
                ItemID.PurpleGoldArchWallpaper,
                ItemID.GrayBrickWallpaper,
                ItemID.StainedGlassPurpleWallpaper,
                ItemID.NavyWithergateWallpaper,
                ItemID.ArtDecoPurpleWallpaper,
                ItemID.WithergateApartmentWallpaper,
                ItemID.NelVariTreehouseWallpaper,
                ItemID.BarnWallpaper,
            }
        },
        {
            DecorationCategory.FloorTiles, new List<int>()
            {
                ItemID.StoneFloorTile,
                ItemID.WorkshopFloorTile,
                ItemID.FloorTile1,
                ItemID.FloorTile2,
                ItemID.FloorTile3,
                ItemID.WoodenPlankFloorTile,
                ItemID.BrickFloorTile,
                ItemID.WhiteStoneFloorTile,
                ItemID.PatternedFloorTile,
                ItemID.OakPlankFloorTile,
                ItemID.WoodFloorTile,
                ItemID.WoodFloorTile,
                ItemID.StoneFloorTile,
                ItemID.WorkshopFloorTile,
                ItemID.FloorTile1,
                ItemID.FloorTile2,
                ItemID.FloorTile3,
                ItemID.WoodenPlankFloorTile,
                ItemID.BrickFloorTile,
                ItemID.WhiteStoneFloorTile,
                ItemID.PatternedFloorTile,
                ItemID.OakPlankFloorTile,
            }
        },        
        {
            DecorationCategory.CraftingTables, new List<int>()
            {
                ItemID.GloriteMiningMachine,
                ItemID.ManaSiphoner,
                ItemID.TicketCounterfeiter,
                ItemID.SeltzerKeg,
                ItemID.FurnaceOld,
                ItemID.AnvilOld,
                ItemID.LoomOld,
                ItemID.FurnitureTable,
                ItemID.CookingPotOld,
                ItemID.Grinder,
                ItemID.LynnAnvil,
                ItemID.JamMaker,
                ItemID.IndustrialCookingStove,
                ItemID.WithergateAnvil,
                ItemID.WithergateFurnace,
                ItemID.AlchemyTable,
                ItemID.JewelersDesk,
                ItemID.CookingPot,
                ItemID.CraftingTable,
                ItemID.Loom,
                ItemID.BakersStation,
                ItemID.FishGrill,
                ItemID.WizardCraftingTable,
                ItemID.Anvil,
                ItemID.Furnace,
                ItemID.FarmersTable,
                ItemID.ConstructionTable,
                ItemID.TileMaker,
                ItemID.PaintersEasel,
                ItemID.BasicFurnitureTable,
                ItemID.AdvancedFurnitureTable,
                ItemID.Composter,
                ItemID.SeedMaker,
                ItemID.IceCreamCart,
                ItemID.Oven,
                ItemID.SushiTable,
                ItemID.Juicer,
                ItemID.ManaComposter,
                ItemID.ElvenFurnitureTable,
                ItemID.ManaAnvil,
                ItemID.ManaInfuserTable,
                ItemID.TeaKettle,
                ItemID.ElvenLoom,
                ItemID.ElvenSeedMaker,
                ItemID.ElvenFurnace,
                ItemID.RecyclingMachine,
                ItemID.MonsterComposter,
                ItemID.MonsterFurnitureTable,
                ItemID.MonsterAnvil,
                ItemID.MonsterSushiTable,
                ItemID.SodaMachine,
                ItemID.MonsterLoom,
                ItemID.MonsterSeedMaker,
                ItemID.MonsterFurnace,
                ItemID.MonsterJuicer,
                ItemID.MonsterCraftingTable,
                ItemID.ElvenCraftingTable,
                ItemID.ElvenJuicer,
                ItemID.CraftingTableOld,
                ItemID.BeeBox,
            }
        },
        {
            DecorationCategory.Fences, new List<int>()
            {
                ItemID.WithergateFence,
                ItemID.WoodenFence,
                ItemID.DeadwoodFence,
                ItemID.WoodenFenceGate,
                ItemID.DeadwoodGate,
                ItemID.HalloweenFence,
                ItemID.WovenWoodFence,
                ItemID.WovenWoodGate,
            }
        },
        {
            DecorationCategory.Rocks, new List<int>()
            {
                ItemID.Rock1b,
                ItemID.Rock2b,
                ItemID.Rock3b,
                ItemID.Rock4b,
                ItemID.Rock5b,
                ItemID.Rock6b,
                ItemID.Rock7b,
                ItemID.Rock1c,
                ItemID.Rock2c,
                ItemID.Rock3c,
                ItemID.Rock4c,
                ItemID.Rock5c,
                ItemID.Rock6c,
                ItemID.Rock7c,
                ItemID.Rock1d,
                ItemID.Rock2d,
                ItemID.Rock3d,
                ItemID.Rock4d,
                ItemID.Rock5d,
                ItemID.Rock6d,
                ItemID.Rock7d,
                ItemID.PlayerFarmNelvariStoneNode,
                ItemID.PlayerFarmWithergateStoneNode,
                ItemID.TourmalineNode,
                ItemID.CitrineNode,
                ItemID.EmeraldNode,
                ItemID.BerylNode,
                ItemID.LapisNode,
                ItemID.TanzaniteNode,
                ItemID.BeeMineRock1x1,
                ItemID.BeeMineRock2x2,
                ItemID.FlowerMineRock1x1,
                ItemID.FlowerMineRock2x2,
                ItemID.TempleMineRock1x1,
                ItemID.TempleMineRock2x2,
                ItemID.MushroomMineRock1x1,
                ItemID.MushroomMineRock2x2,
                ItemID.SparklingDragonScaleRock,
                ItemID.SharpDragonScaleRock,
                ItemID.ToughDragonScaleRock,
                ItemID.ShardRockSmall,
                ItemID.ShardRockMedium,
                ItemID.ShardRockLarge,
                ItemID.PumpkinMineRock2x2,
                ItemID.CandyMainMineRock2x2,
                ItemID.HeavystoneNode,
                ItemID.DizziteNode,
                ItemID.ElvenHeavystoneNode,
                ItemID.ElvenStoneNode,
                ItemID.DeadHeavystoneNode,
                ItemID.DeadStoneNode,
                ItemID.CopperOreNode,
                ItemID.IronOreNode,
                ItemID.AdamantOreNode,
                ItemID.MithrilOreNode,
                ItemID.SuniteOreNode,
                ItemID.GoldOreNode,
                ItemID.CoalOreNode,
                ItemID.GloriteOreNode,
                ItemID.Sapphirenode,
                ItemID.Rubynode,
                ItemID.Amethystnode,
                ItemID.Diamondnode,
                ItemID.Havenitenode,
                ItemID.StoneNode1,
                ItemID.StoneNode2,
                ItemID.StoneNode3,
                ItemID.StoneNode4,
                ItemID.StoneNode5,
                ItemID.StoneNode6,
                ItemID.StoneNode7,
                ItemID.PlayerFarmStoneNode,
                ItemID.Largerock1,
                ItemID.Largerock2,
                ItemID.Largerock3,
                ItemID.Largerock4,
                ItemID.KrustyGoldOreNode,
            }
        },
        {
            DecorationCategory.Foliage, new List<int>()
            {
                ItemID.Foliage3,
                ItemID.Foliage7,
                ItemID.Foliage9,
                ItemID.Foliage10,
                ItemID.Foliage11,
                ItemID.Foliage12,
                ItemID.Foliage13,
                ItemID.Foliage14,
                ItemID.Foliage15,
                ItemID.Foliage16,
                ItemID.Foliage17,
                ItemID.Foliage18,
                ItemID.Foliage19,
                ItemID.Foliage20,
                ItemID.Foliage21,
                ItemID.Foliage22,
                ItemID.Foliage23,
                ItemID.Foliage24,
            }
        },
        {
            DecorationCategory.Animals, new List<int>()
            {
                ItemID.Cow,
                ItemID.Chicken,
                ItemID.Sheep,
                ItemID.BabyStump,
                ItemID.SilkMoth,
                ItemID.BabyGriffon,
                ItemID.Squirrel,
                ItemID.WhiteBabyDragon,
                ItemID.RockSprite,
                ItemID.WaterSprite,
                ItemID.FireSprite,
                ItemID.WindSprite,
                ItemID.WildCat,
                ItemID.Werewolf,
                ItemID.Pig,
                ItemID.Snaccoon,
                ItemID.RamberryBush,
                ItemID.MooshroomCow,
                ItemID.BabyPhoenix,
                ItemID.FaeFox,
                ItemID.Fishfrog,
                ItemID.MetallicDragon,
                ItemID.Sandworm,
                ItemID.CementSlime,
                ItemID.TarSlime,
                ItemID.CrystalBat,
                ItemID.SilkWyrm,
                ItemID.Mimic,
                ItemID.Ooey,
                ItemID.Tilia,
                ItemID.Axie,
                ItemID.Myrtle,
                ItemID.Gus,
                ItemID.Sizzle,
                ItemID.Bartleby,
                ItemID.Revi,
                ItemID.Pix,
                ItemID.Kelsie,
                ItemID.Pud,
                ItemID.Wixxy,
                ItemID.Graggle,
                ItemID.Gayle,
                ItemID.Darter,
                ItemID.Grubby,
                ItemID.Spirix,
                ItemID.RedShiver,
                ItemID.OrangeShiver,
                ItemID.YellowShiver,
                ItemID.GreenShiver,
                ItemID.BlueShiver,
                ItemID.PurpleShiver,
                ItemID.PinkShiver,
                ItemID.Octavius,
                ItemID.OrangeBunny,
                ItemID.GreyBunny,
                ItemID.BrownBunny,
                ItemID.BlackBunny,
                ItemID.SpottedBunny,
                ItemID.RedUnicorn,
                ItemID.OrangeUnicorn,
                ItemID.YellowUnicorn,
                ItemID.GreenUnicorn,
                ItemID.BlueUnicorn,
                ItemID.PurpleUnicorn,
                ItemID.PinkUnicorn,
                ItemID.FlamingUnicorn,
                ItemID.WhiteBuppy,
                ItemID.BlackBuppy,
                ItemID.SpottedBuppy,
                ItemID.BrownBuppy,
                ItemID.YellowSmolder,
                ItemID.PurpleSmolder,
                ItemID.BlackSmolder,
                ItemID.WhiteSmolder,
                ItemID.BlueSmolder,
                ItemID.GreenSmolder,
                ItemID.TealBubbles,
                ItemID.BlueBubbles,
                ItemID.PinkBubbles,
                ItemID.FlameBubbles,
                ItemID.RedKit,
                ItemID.OrangeKit,
                ItemID.YellowKit,
                ItemID.GreenKit,
                ItemID.PurpleKit,
                ItemID.PinkKit,
                ItemID.BlackKit,
                ItemID.OrangePercy,
                ItemID.GreenPercy,
                ItemID.BluePercy,
                ItemID.PurplePercy,
                ItemID.PinkPercy,
                ItemID.BlackPercy,
            }
        },        
        {
            DecorationCategory.Scarecrows, new List<int>()
            {
                ItemID.SpringScarecrow,
                ItemID.ExplorationTotem,
                ItemID.WithergateTotem,
                ItemID.FireFertilizerTotem,
                ItemID.WateringCanTotem,
                ItemID.RoyalTotem,
                ItemID.NelVariTotem,
                ItemID.CombatTotem,
                ItemID.FallScarecrow,
                ItemID.SummerScarecrow,
                ItemID.WinterScarecrow,
                ItemID.FishingTotem,
                ItemID.MiningTotem,
                ItemID.FarmingTotem,
                ItemID.FallTotem,
                ItemID.SpringTotem,
                ItemID.SummerTotem,
                ItemID.WinterTotem,
                ItemID.SunHavenTotem,
                ItemID.ScarecrowOld,
            }
        },
        {
            DecorationCategory.Buildings, new List<int>()
            {
                ItemID.House,
                ItemID.Barn,
                ItemID.BasicShed,
                ItemID.ElvenBarn,
                ItemID.Tier2HouseUpgrade,
                ItemID.Tier3HouseUpgrade,
                ItemID.CraftingWorkshop,
                ItemID.NelvariWorkshop,
                ItemID.WithergateWorkshop,
                ItemID.NelVariButterflyGarden,
                ItemID.Warehouse,
                ItemID.DemolitionKit,
                ItemID.Silo,
                ItemID.ChickenCoop,
                ItemID.CobbleStoneBridge,
                ItemID.StoneBridge,
                ItemID.WoodBridge,
                ItemID.ArchedBridge,
                ItemID.MarbleBridge,
                ItemID.ElvenBridge,
                ItemID.SpringBridge,
                ItemID.MonsterBridge,
                ItemID.ModernBridge,
                ItemID.ZenBridge,
                ItemID.ToyBridge,
                ItemID.GreenhouseSpring,
                ItemID.GreenhouseSummer,
                ItemID.GreenhouseFall,
                ItemID.GreenhouseWinter,
            }
        },        
        {
            DecorationCategory.Seeds, new List<int>()
            {
                ItemID.WheatSeeds,
                ItemID.CornSeeds,
                ItemID.PotatoSeeds,
                ItemID.TomatoSeeds,
                ItemID.DemonSeeds,
                ItemID.SnappySeeds,
                ItemID.CarrotSeeds,
                ItemID.ShimmerootSeeds,
                ItemID.PepperSeeds,
                ItemID.OnionSeeds,
                ItemID.GreenrootSeeds,
                ItemID.CinnaberrySeeds,
                ItemID.LettuceSeeds,
                ItemID.RiceSeeds,
                ItemID.EggplantSeeds,
                ItemID.KrakenKaleSeeds,
                ItemID.MoonplantSeeds,
                ItemID.SuckerstemSeeds,
                ItemID.TombmelonSeeds,
                ItemID.RazorstalkSeeds,
                ItemID.SoulOrbSeeds,
                ItemID.GrapeSeeds,
                ItemID.WaterFruitSeeds,
                ItemID.FireFruitSeeds,
                ItemID.RockFruitSeeds,
                ItemID.WindChimeSeeds,
                ItemID.DragonFruitSeeds,
                ItemID.WalkChoySeeds,
                ItemID.ShiiwalkiMushroomSeeds,
                ItemID.IndiglowSeeds,
                ItemID.AcornSeeds,
                ItemID.CatTailSeeds,
                ItemID.ManaGemSeeds,
                ItemID.DarknessEssenceSeeds,
                ItemID.GuavaBerrySeeds,
                ItemID.PumpkinSeeds,
                ItemID.HopsSeeds,
                ItemID.SodaPopCropSeeds,
                ItemID.FizzyFruitSeeds,
                ItemID.TurnipSeeds,
                ItemID.HeatFruitSeeds,
                ItemID.MarshmallowBeanSeeds,
                ItemID.ButternutSeeds,
                ItemID.BarleySeeds,
                ItemID.YamSeeds,
                ItemID.TeaLeafSeeds,
                ItemID.GhostPepperSeeds,
                ItemID.KaleSeeds,
                ItemID.StormelonSeeds,
                ItemID.LemonSeeds,
                ItemID.ArmoranthSeeds,
                ItemID.ChocoberrySeeds,
                ItemID.CloverSeeds,
                ItemID.PineappleSeeds,
                ItemID.MelonSeeds,
                ItemID.HeartBerrySeeds,
                ItemID.CoffeeBeanSeeds,
                ItemID.GarlicSeeds,
                ItemID.MangoSeeds,
                ItemID.DurianSeeds,
                ItemID.BalloonFruitSeeds,
                ItemID.BlueMoonFruitSeeds,
                ItemID.HexagonBerrySeeds,
                ItemID.StarFruitSeeds,
                ItemID.SnowBallSeeds,
                ItemID.BlizzardBerrySeeds,
                ItemID.PythagoreanBerrySeeds,
                ItemID.CranberrySeeds,
                ItemID.KiwiBerrySeeds,
                ItemID.GreenBeanSeeds,
                ItemID.PeaSeeds,
                ItemID.WatermelonVineSeeds,
                ItemID.CottonSeeds, 
                ItemID.HoneysuckleSeeds,
                ItemID.CandyCaneSeeds,
                ItemID.SnowPeaSeeds,
                ItemID.SunOrbSeeds,
                ItemID.HoneyFlowerSeeds,
                ItemID.LavenderSeeds,
                ItemID.HibiscusSeeds,
                ItemID.LilySeeds,
                ItemID.OrchidSeeds,
                ItemID.SunflowerSeeds,
                ItemID.RedRoseSeeds,
                ItemID.BlueRoseSeeds,
                ItemID.TulipSeeds,
                ItemID.LotusSeeds,
                ItemID.DaisySeeds,
                ItemID.ElementalSeeds,
                ItemID.SugarCaneSeeds,
                ItemID.BeetSeeds,
                ItemID.PurpleEggplantSeeds,
                ItemID.BrrNanaSeeds,
            }
        },
        {
            DecorationCategory.DLC, new List<int>()
            {
                ItemID.PirateAnchor,
                ItemID.PirateBed,
                ItemID.PirateCannon,
                ItemID.PirateChair,
                ItemID.PirateChest,
                ItemID.PirateHammock,
                ItemID.PirateTable,
                ItemID.PirateTreasureMap,
                ItemID.PirateWardrobe,
                ItemID.PirateWoodPost,
                ItemID.SeasideBed,
                ItemID.SeasideChair,
                ItemID.SeasideChest,
                ItemID.SeasideEndTable,
                ItemID.SeasideLamp,
                ItemID.SeasideTable,
                ItemID.SeasideWardrobe,
                ItemID.BlueSeasideShellRug,
                ItemID.BlueSeasideStarfishRug,
                ItemID.PinkSeasideShellRug,
                ItemID.PinkSeasideStarfishRug,
                ItemID.MushroomBed,
                ItemID.MushroomBookshelf,
                ItemID.MushroomCarpet,
                ItemID.MushroomCoatRack,
                ItemID.MushroomTable,
                ItemID.MushroomEndTable,
                ItemID.RedMushroomDecoration,
                ItemID.LightBrownMushroomDecoration,
                ItemID.CyberpopThrone,
                ItemID.CyberpopBicycle,
                ItemID.CyberpopHoverBike,
                ItemID.CyberpopMotorcycle,
                ItemID.CyberpopBed,
                ItemID.CyberpopCouch,
                ItemID.CyberpopStudentChest,
                ItemID.CyberpopWardrobe,
                ItemID.CyberpopArcCapacitor,
                ItemID.CyberpopRecordPlayer,
                ItemID.CyberpopStudentChair,
                ItemID.CyberpopGlobe,
                ItemID.CyberpopDesk,
                ItemID.CyberpopTable,
                ItemID.CyberpopRug,
                ItemID.RocknRollCouch,
                ItemID.RocknRollAmp,
                ItemID.RocknRollBlackGuitar,
                ItemID.RocknRollRedGuitar,
                ItemID.RocknRollWardrobe,
                ItemID.RocknRollLamp,
                ItemID.RocknRollGoldRecordAward,
                ItemID.RocknRollBed,
                ItemID.RocknRollTable,
                ItemID.RocknRollEndTable,
                ItemID.RocknRollBlackRug,
                ItemID.RocknRollRedRug,
                ItemID.SpiritOrb,
                ItemID.SpiritPetalLamp,
                ItemID.SpiritPetalWardrobe,
                ItemID.SpiritPetalCouch,
                ItemID.SpiritPetalChair,
                ItemID.SpiritPetalEndTable,
                ItemID.SpiritPetalTable,
                ItemID.SpiritPetalRug,
                ItemID.SpiritPetalBed,
                ItemID.SpookyRug,
                ItemID.SpookyBed,
                ItemID.SpookyWardrobe,
                ItemID.SpookyCouch,
                ItemID.SpookyChair,
                ItemID.SpookyEndTable,
                ItemID.SpookyTable,
                ItemID.SpookyPumpkinCauldron,
                ItemID.SpookyStackofPumpkins,
            }
        },
        {
            DecorationCategory.Pets, new List<int>()
            {
                ItemID.Ellis,
                ItemID.Lewey,
                ItemID.Ixi,
                ItemID.S1FER,
                ItemID.QU4CK,
                ItemID.MOUS3,
                ItemID.Daydream,
                ItemID.Funky,
                ItemID.Slash,
                ItemID.Scuttles,
                ItemID.Sam,
                ItemID.Mips,
                ItemID.Booshroom,
                ItemID.Buppy,
                ItemID.Kitty,
                ItemID.Bunny,
                ItemID.PrinceFrog,
                ItemID.Shiver,
                ItemID.Bubbles,
                ItemID.Smolder,
                ItemID.Nimbus,
                ItemID.Grimbus,
                //ItemID.BabyTiger, kickstarter
                //ItemID.BabyDragon, kickstarter
                ItemID.Unicorn,
                ItemID.BlueberrySprinkles,
                ItemID.MisterSlither,
                ItemID.Raccoon,
                ItemID.ChocolateSprinkles,
                ItemID.MintSprinkles,
                ItemID.Kit,
                ItemID.Percy,
                ItemID.StrawberrySprinkles,
                ItemID.StripedMisterSlither,
                ItemID.BlackKitty,
                ItemID.BlackUnicorn,
                ItemID.Weedy,
                ItemID.Pebbles,
                ItemID.LanternSpirit,
                ItemID.Dizzlette,
                ItemID.Hermy,
                ItemID.Grumbles,
                ItemID.PrinceSlimiusVXXIII,
                ItemID.Bloom,
                ItemID.Shortcake,
                ItemID.Rustle,
                ItemID.Brrrry,
                ItemID.WizardToad,
                ItemID.WitchCat,
                ItemID.Rexxie,
                ItemID.WalkChoyPet,
                ItemID.ShiiwalkiMushroomPet,
                ItemID.GreyKitty,
                ItemID.TuxedoKitty,
                ItemID.OrangeKitty,
                ItemID.CalicoKitty,
                ItemID.RedMisterSlither,
                ItemID.OrangeMisterSlither,
                ItemID.YellowMisterSlither,
                ItemID.BlueMisterSlither,
                ItemID.PurpleMisterSlither,
                ItemID.VanillaSprinkles,
                ItemID.MatchaSprinkles,
                ItemID.Audrey,
                ItemID.Draco,
                ItemID.Jad,
                ItemID.Leechums,
                ItemID.Octonot,
                ItemID.Skerbs,
                ItemID.Brimmy,
                ItemID.Webster,
                ItemID.Nevermore,
                ItemID.Noire,
                ItemID.Fangy,
                ItemID.Pips,
                ItemID.Chipper,
                ItemID.Pinkadee,
                ItemID.Ursil,
                ItemID.Sweetie,
                ItemID.Buffo,
                ItemID.Grimmy,
                ItemID.Ollie,
                ItemID.Spoops,
                ItemID.Beelsie,
                ItemID.Crumble,
                ItemID.Hubie,
                ItemID.Kernie,
                ItemID.Zeb,
                ItemID.Cornelius,
                ItemID.Tribert,
                ItemID.Jackie,
                ItemID.Vix,
                ItemID.Griffith,
                ItemID.Dean,
                ItemID.Kappy,
                ItemID.Zippy,
                ItemID.Mimi,
                ItemID.Bucky,
                ItemID.Orville,
                ItemID.Woodie,
                ItemID.Tilia,
                ItemID.Axie,
                ItemID.Myrtle,
                ItemID.Gus,
                ItemID.Sizzle,
                ItemID.Bartleby,
                ItemID.Revi,
                ItemID.Pix,
                ItemID.Kelsie,
                ItemID.Pud,
                ItemID.Wixxy,
                ItemID.Graggle,
                ItemID.Gayle,
                ItemID.Darter,
                ItemID.Grubby,
                ItemID.Spirix,
                ItemID.RedShiver,
                ItemID.OrangeShiver,
                ItemID.YellowShiver,
                ItemID.GreenShiver,
                ItemID.BlueShiver,
                ItemID.PurpleShiver,
                ItemID.PinkShiver,
                ItemID.OrangeBunny,
                ItemID.GreyBunny,
                ItemID.BrownBunny,
                ItemID.BlackBunny,
                ItemID.SpottedBunny,
                ItemID.RedUnicorn,
                ItemID.OrangeUnicorn,
                ItemID.YellowUnicorn,
                ItemID.GreenUnicorn,
                ItemID.BlueUnicorn,
                ItemID.PurpleUnicorn,
                ItemID.PinkUnicorn,
                ItemID.FlamingUnicorn,
                ItemID.WhiteBuppy,
                ItemID.BlackBuppy,
                ItemID.SpottedBuppy,
                ItemID.BrownBuppy,
                ItemID.YellowSmolder,
                ItemID.PurpleSmolder,
                ItemID.BlackSmolder,
                ItemID.WhiteSmolder,
                ItemID.BlueSmolder,
                ItemID.GreenSmolder,
                ItemID.TealBubbles,
                ItemID.BlueBubbles,
                ItemID.PinkBubbles,
                ItemID.FlameBubbles,
                ItemID.RedKit,
                ItemID.OrangeKit,
                ItemID.YellowKit,
                ItemID.GreenKit,
                ItemID.PurpleKit,
                ItemID.PinkKit,
                ItemID.BlackKit,
                ItemID.OrangePercy,
                ItemID.GreenPercy,
                ItemID.BluePercy,
                ItemID.PurplePercy,
                ItemID.PinkPercy,
                ItemID.BlackPercy,
                ItemID.Willo,
            }
        },
    };
}