namespace CreativeMode;

public enum DecorationCategory
{
    None = 0,
    Beds = 1,
    Bookcases = 2,
    HutchesLockers = 3,
    Instruments = 4,
    Paintings = 5,
    Plants = 6,
    WallDisplays = 7,
    Statues = 8,
    Hammocks = 9,
    Armory = 10,
    MiscDecor = 11,
    Winter = 12,
    Halloween = 13,
    Lighting = 14,
    PetItems = 15,
    Plushies = 16,
    Rugs = 17,
    Seating = 18,
    Storage = 19,
    Surfaces = 20,
    Clutter = 21,
    Appliances = 22,
    SellingPortals = 23,
    Mailboxes = 24,
    Windows = 25,
    Wallpaper = 26,
    FloorTiles = 27,
    CraftingTables = 28,
    Fences = 29,
    Foliage = 30,
    Rocks = 31,
    Scarecrows = 32,
    Animals = 33,
    Pets = 34,
    Buildings = 35,
    Seeds = 36,
    DLC = 37,
}